/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const init_panic_hook: () => void;
export const __wbg_frequencyplayer_free: (a: number, b: number) => void;
export const __wbg_get_frequencyplayer_beat_freq: (a: number) => number;
export const __wbg_get_frequencyplayer_carrier_freq: (a: number) => number;
export const __wbg_get_frequencyplayer_delay_mix: (a: number) => number;
export const __wbg_get_frequencyplayer_drive_amt: (a: number) => number;
export const __wbg_get_frequencyplayer_fm_depth: (a: number) => number;
export const __wbg_get_frequencyplayer_fm_ratio: (a: number) => number;
export const __wbg_get_frequencyplayer_is_binaural: (a: number) => number;
export const __wbg_get_frequencyplayer_lfo_amt: (a: number) => number;
export const __wbg_get_frequencyplayer_noise_amt: (a: number) => number;
export const __wbg_get_frequencyplayer_reverb_mix: (a: number) => number;
export const __wbg_get_frequencyplayer_sample_rate: (a: number) => number;
export const __wbg_set_frequencyplayer_beat_freq: (a: number, b: number) => void;
export const __wbg_set_frequencyplayer_carrier_freq: (a: number, b: number) => void;
export const __wbg_set_frequencyplayer_delay_mix: (a: number, b: number) => void;
export const __wbg_set_frequencyplayer_drive_amt: (a: number, b: number) => void;
export const __wbg_set_frequencyplayer_fm_depth: (a: number, b: number) => void;
export const __wbg_set_frequencyplayer_fm_ratio: (a: number, b: number) => void;
export const __wbg_set_frequencyplayer_is_binaural: (a: number, b: number) => void;
export const __wbg_set_frequencyplayer_lfo_amt: (a: number, b: number) => void;
export const __wbg_set_frequencyplayer_noise_amt: (a: number, b: number) => void;
export const __wbg_set_frequencyplayer_reverb_mix: (a: number, b: number) => void;
export const __wbg_set_frequencyplayer_sample_rate: (a: number, b: number) => void;
export const frequencyplayer_new: (a: number) => number;
export const frequencyplayer_process_stereo: (a: number, b: number, c: number, d: any, e: number, f: number, g: any) => void;
export const frequencyplayer_release: (a: number) => void;
export const frequencyplayer_set_binaural: (a: number, b: number, c: number) => void;
export const frequencyplayer_set_drive: (a: number, b: number) => void;
export const frequencyplayer_set_envelope: (a: number, b: number, c: number, d: number, e: number) => void;
export const frequencyplayer_set_filter: (a: number, b: number, c: number) => void;
export const frequencyplayer_set_fm: (a: number, b: number, c: number) => void;
export const frequencyplayer_set_freq: (a: number, b: number) => void;
export const frequencyplayer_set_fx: (a: number, b: number, c: number) => void;
export const frequencyplayer_set_lfo: (a: number, b: number, c: number) => void;
export const frequencyplayer_set_noise: (a: number, b: number) => void;
export const frequencyplayer_trigger: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_start: () => void;
